### PR TITLE
ANC Fixes for Some Russian/Chinese Units

### PR DESCRIPTION
**Pull request by Bhavukverma17**

### CODE REVIEW

**Comment by jjpprrrr** [comment]
Hi! Thanks for the patch. I have two comments:

1. Is there a way to apply the change to dipper only? For example, is it possible to use the mixer path static overlay in device/xiaomi/dipper to change the IIR0 bands? I'm asking because polaris (also using sdm845-common) does not have this issue, and I would like to avoid changing sdm845-common directly in case it breaks something on other sdm845 devices.
2. I am not sure what the IIR0 bands do, and I have concerns about whether they should be set to 1 all the time. Looking at the mixer path, I see that "sidetone-iir" path sets these bands to 1. I was wondering if similar things can be done to fix the echo issue.

**Comment by Bhavukverma17** [comment]
Most Probably Setting values of IIR0 Enable bands to 1 Will not cause any issue to polaris (but still needs to be tested) As IIR0 Bands will filter out the unwanted Noise & interference to specific Frequency range of IIR Filters.

To test on Polaris, Need a tester who can Try enabling IIR0 Enable Bands using Root 
Screenshot_20230402-090431_MT_Manager

Thanks 🙏

**Comment by jjpprrrr** [comment]
Again, I would rather not change sdm845-common directly. Can you please add the IIR0 band ctl to this file and see if it fixes the issue?

https://github.com/PixelExperience-Devices/device_xiaomi_dipper/blob/thirteen/audio/mixer_paths_overlay_static.xml

**Comment by Bhavukverma17** [comment]
Sir, Thanks for your response. I Just tried, it fixed my issue. Shoud i make commit in Mixer_paths_overlay_static.xml for dipper ?

**Pull request closed without merging**
